"  git clone https://github.com/vim/vim.git
" cd vim/src *  make
set digraph
set nocompatible
set backspace=indent,eol,start
set fileencodings=utf-8
set termencoding=utf-8
set encoding=utf-8
set number
set relativenumber
set background=dark
set cursorline
" set cursorcolumn
set mouse=a
set selection=exclusive
set selectmode=mouse,key
set showmatch
set clipboard=unnamedplus
set shiftwidth=4
set tabstop=4
set softtabstop=4
set smarttab
set expandtab
set autoindent
set cindent
set t_Co=256
set ignorecase
" set paste
" set list
" set listchars=precedes:«,extends:»,multispace:···,trail:.
set laststatus=2
set ruler
set nowrap
set ff=unix
set showcmd
set history=1000
set nobackup
set noswapfile
filetype on
filetype indent on
filetype plugin on
filetype plugin indent on
syntax enable
syntax on

" autocmd BufWritePost $MYVIMRC source $MYVIMRC
let g:molokai_original = 1
let g:rehash256 = 1
let mapleader="\<Space>"
colorscheme molokai
" Insert --
inoremap jk <ESC>:w<CR>
inoremap df <ESC>:w<CR> 
inoremap ( ()<Left>
inoremap { {}<Left>
inoremap [ []<Left>
inoremap < <><Left>
inoremap ) <ESC>f)a
inoremap } <ESC>f}a
inoremap ] <ESC>f]a
inoremap > <ESC>f>a
inoremap <C-a> <ESC>ggVG
inoremap <C-c> <ESC>y<ESC>a
inoremap <C-v> <ESC>p<ESC>a
inoremap <C-z> <ESC>u<ESC>a
inoremap <C-s> <ESC>:w<CR>a
inoremap <C-q> <ESC>:q<CR>
inoremap <C-j> <Down>
inoremap <C-k> <Up>

" Normal -- 
nnoremap gh ^
nnoremap gl $
nnoremap K f<Space>r<CR>
" nnoremap cs"' F"r'f"r'b
nnoremap ds" F"xf"xb
nnoremap ds' F'xf'xb
nnoremap ds( F(xf)xb
nnoremap ds< F<xf>xb
nnoremap ds[ F[xf]xb
nnoremap ds{ F{xf}xb
nnoremap <leader>pa :set paste<CR>
nnoremap <leader>np :set nopaste<CR>
nnoremap <silent> <leader>al :quitall<CR>
nnoremap <silent> <leader>so :source %<CR>
nnoremap <silent> <leader>vi :vsplit ~/.vim/vimrc<CR>
nnoremap <silent> <leader>zs :vsplit ~/.zshrc<CR>
nnoremap <silent> <leader>ba :vsplit ~/.bashrc<CR>
nnoremap <silent> <leader>bd :bdelete<CR>
nnoremap <silent> <leader>te :terminal<CR>
nnoremap <silent> <leader>nh :nohlsearch<CR>
nnoremap <silent> <leader>e :Vexplore<CR>


" Resize with arrows
nnoremap <silent> <C-Up> :resize +2<CR>                                        
nnoremap <silent> <C-Down> :resize -2<CR>
nnoremap <silent> <C-Left> :vertical resize -2<CR>
nnoremap <silent> <C-Right> :vertical resize +2<CR>

" Navigate buffers
nnoremap <silent> <S-l> :bnext<CR>
nnoremap <silent> <S-h> :bprevious<CR>
" 
nnoremap <C-h> <C-w>h 
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" Visual --
" Stay in indent mode
vnoremap < <gv
vnoremap > >gv
" Move text up and down
vnoremap J :m .+1<CR>
vnoremap K :m .-2<CR>
vnoremap <A-j> :m .+1<CR>
vnoremap <A-k> :m .-2<CR>
vnoremap p "_dP

" Visual Block --
" Move text up and down
xnoremap J :move '>+1<CR>gv
xnoremap K :move '<-2<CR>gv
xnoremap <A-j> :move '>+1<CR>gv
xnoremap <A-k> :move '<-2<CR>gv

" Terminal --
" Better terminal navigation
tnoremap <C-w>h <C-\><C-N><C-w>h
tnoremap <C-w>j <C-\><C-N><C-w>j
tnoremap <C-w>k <C-\><C-N><C-w>k
tnoremap <C-w>l <C-\><C-N><C-w>l
tnoremap <C-w>q <C-\><C-N>:q!<CR>

" cursors style
let &t_SI.="\e[5 q" "SI = INSERT mode
let &t_SR.="\e[4 q" "SR = REPLACE mode
let &t_EI.="\e[2 q" "EI = NORMAL mode
"
